
package wcompensar.caf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CAFSoap", targetNamespace = "http://WCompensar/CAF")
@XmlSeeAlso({
    caf.wcompensar.ObjectFactory.class,
    com.compensar.verticalsalud_sap.consultar.ObjectFactory.class,
    com.tibco.schemas.compensarleh.resources.eim.common.servicecommon.ObjectFactory.class,
    wcompensar.caf.ObjectFactory.class
})
public interface CAFSoap {


    /**
     * Consulta del afiliados a multiples programas
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param iOpc
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MultiAfiliado", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/MultiAfiliado")
    @WebResult(name = "MultiAfiliadoResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "MultiAfiliado", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.MultiAfiliado")
    @ResponseWrapper(localName = "MultiAfiliadoResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.MultiAfiliadoResponse")
    public String multiAfiliado(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        String dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Salario minimo legal vigente
     * 
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SMLV", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/SMLV")
    @WebResult(name = "SMLVResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "SMLV", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.SMLV")
    @ResponseWrapper(localName = "SMLVResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.SMLVResponse")
    public String smlv(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl);

    /**
     * Consultas FONEDE
     * 
     * @param sParametros
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fonede", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/Fonede")
    @WebResult(name = "FonedeResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "Fonede", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.Fonede")
    @ResponseWrapper(localName = "FonedeResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.FonedeResponse")
    public String fonede(
        @WebParam(name = "sParametros", targetNamespace = "http://WCompensar/CAF")
        String sParametros);

    /**
     * Consulta de empresas
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param iDep
     * @param iOpc
     * @param sPrograma
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Empresa", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/Empresa")
    @WebResult(name = "EmpresaResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "Empresa", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.Empresa")
    @ResponseWrapper(localName = "EmpresaResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.EmpresaResponse")
    public String empresa(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        double dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo,
        @WebParam(name = "iDep", targetNamespace = "http://WCompensar/CAF")
        int iDep,
        @WebParam(name = "sPrograma", targetNamespace = "http://WCompensar/CAF")
        String sPrograma,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Consulta alfabetica de empresas
     * 
     * @param sParametros
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EmpresaAlfa", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/EmpresaAlfa")
    @WebResult(name = "EmpresaAlfaResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "EmpresaAlfa", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.EmpresaAlfa")
    @ResponseWrapper(localName = "EmpresaAlfaResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.EmpresaAlfaResponse")
    public String empresaAlfa(
        @WebParam(name = "sParametros", targetNamespace = "http://WCompensar/CAF")
        String sParametros);

    /**
     * Entrada a consultas varias para Labsys
     * 
     * @param sParametros
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Consultas", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/Consultas")
    @WebResult(name = "ConsultasResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "Consultas", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.Consultas")
    @ResponseWrapper(localName = "ConsultasResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultasResponse")
    public String consultas(
        @WebParam(name = "sParametros", targetNamespace = "http://WCompensar/CAF")
        String sParametros);

    /**
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaDeCambioDeIdentificacion", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/ConsultaDeCambioDeIdentificacion")
    @WebResult(name = "ConsultaDeCambioDeIdentificacionResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "ConsultaDeCambioDeIdentificacion", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaDeCambioDeIdentificacion")
    @ResponseWrapper(localName = "ConsultaDeCambioDeIdentificacionResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaDeCambioDeIdentificacionResponse")
    public String consultaDeCambioDeIdentificacion(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        double dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo);

    /**
     * Consulta Información del afiliado
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param iOpc
     * @param sPrimerApellido
     * @param sSegundoApellido
     * @param sSegundoNombre
     * @param sApl
     * @param sPrimerNombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InfoAfiliado", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF-service0.serviceagent/CAFSoapEndpoint0/InfoAfiliado")
    @WebResult(name = "InfoAfiliadoResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "InfoAfiliado", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.InfoAfiliado")
    @ResponseWrapper(localName = "InfoAfiliadoResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.InfoAfiliadoResponse")
    public String infoAfiliado(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        String dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc,
        @WebParam(name = "sPrimerNombre", targetNamespace = "http://WCompensar/CAF")
        String sPrimerNombre,
        @WebParam(name = "sSegundoNombre", targetNamespace = "http://WCompensar/CAF")
        String sSegundoNombre,
        @WebParam(name = "sPrimerApellido", targetNamespace = "http://WCompensar/CAF")
        String sPrimerApellido,
        @WebParam(name = "sSegundoApellido", targetNamespace = "http://WCompensar/CAF")
        String sSegundoApellido);

    /**
     * Parametros
     * 
     * @param sCodigo
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DatosBasicos", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/DatosBasicos")
    @WebResult(name = "DatosBasicosResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "DatosBasicos", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.DatosBasicos")
    @ResponseWrapper(localName = "DatosBasicosResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.DatosBasicosResponse")
    public String datosBasicos(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "sCodigo", targetNamespace = "http://WCompensar/CAF")
        String sCodigo);

    /**
     * Consulta Sede de atencion a la que este asignada
     * 
     * @param iOpc
     * @param sParametros
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarSede", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/ConsultarSede")
    @WebResult(name = "ConsultarSedeResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "ConsultarSede", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultarSede")
    @ResponseWrapper(localName = "ConsultarSedeResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultarSedeResponse")
    public String consultarSede(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "sParametros", targetNamespace = "http://WCompensar/CAF")
        String sParametros,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Ciudades de cundinamarca
     * 
     * @param iOpc
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ciudades", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/Ciudades")
    @WebResult(name = "CiudadesResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "Ciudades", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.Ciudades")
    @ResponseWrapper(localName = "CiudadesResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.CiudadesResponse")
    public String ciudades(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Consultas en Clientes
     * 
     * @param iOpc
     * @param sParametros
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultasAF", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/ConsultasAF")
    @WebResult(name = "ConsultasAFResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "ConsultasAF", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultasAF")
    @ResponseWrapper(localName = "ConsultasAFResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultasAFResponse")
    public String consultasAF(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "sParametros", targetNamespace = "http://WCompensar/CAF")
        String sParametros,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Consulta del afiliado
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param iOpc
     * @param sPrograma
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Afiliado", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/Afiliado")
    @WebResult(name = "AfiliadoResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "Afiliado", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.Afiliado")
    @ResponseWrapper(localName = "AfiliadoResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.AfiliadoResponse")
    public String afiliado(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        String dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo,
        @WebParam(name = "sPrograma", targetNamespace = "http://WCompensar/CAF")
        String sPrograma,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * Consulta datos generales de parametrizacion, Siempre que no requiera parametros de filtrado
     * 
     * @param iOpc
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaDatosBasicos", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/ConsultaDatosBasicos")
    @WebResult(name = "ConsultaDatosBasicosResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "ConsultaDatosBasicos", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaDatosBasicos")
    @ResponseWrapper(localName = "ConsultaDatosBasicosResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaDatosBasicosResponse")
    public String consultaDatosBasicos(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

    /**
     * 
     * @param dIdentificacion
     * @param iTipo
     * @param iOpc
     * @param sApl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaMaestroDeTarjetas", action = "/Services/Utility/caf/WS/Implementation/ISICOM-CAF.serviceagent/CAFSoapEndpoint/ConsultaMaestroDeTarjetas")
    @WebResult(name = "ConsultaMaestroDeTarjetasResult", targetNamespace = "http://WCompensar/CAF")
    @RequestWrapper(localName = "ConsultaMaestroDeTarjetas", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaMaestroDeTarjetas")
    @ResponseWrapper(localName = "ConsultaMaestroDeTarjetasResponse", targetNamespace = "http://WCompensar/CAF", className = "wcompensar.caf.ConsultaMaestroDeTarjetasResponse")
    public String consultaMaestroDeTarjetas(
        @WebParam(name = "sApl", targetNamespace = "http://WCompensar/CAF")
        String sApl,
        @WebParam(name = "dIdentificacion", targetNamespace = "http://WCompensar/CAF")
        double dIdentificacion,
        @WebParam(name = "iTipo", targetNamespace = "http://WCompensar/CAF")
        int iTipo,
        @WebParam(name = "iOpc", targetNamespace = "http://WCompensar/CAF")
        int iOpc);

}
