
package wcompensar.caf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import caf.wcompensar.ConsultarUsuarioRequest;
import caf.wcompensar.ConsultarUsuarioResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InformacionUsuarioSoap", targetNamespace = "http://WCompensar/CAF")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    caf.wcompensar.ObjectFactory.class,
    com.compensar.verticalsalud_sap.consultar.ObjectFactory.class,
    com.tibco.schemas.compensarleh.resources.eim.common.servicecommon.ObjectFactory.class,
    wcompensar.caf.ObjectFactory.class
})
public interface InformacionUsuarioSoap {


    /**
     * 
     * @param parameter
     * @return
     *     returns caf.wcompensar.ConsultarUsuarioResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "ConsultarUsuario", action = "/WebService/Implementation/ISICOM-CAF.serviceagent/InformacionUsuarioSoapEndpoint1/ConsultarUsuario")
    @WebResult(name = "ConsultarUsuarioResponse", targetNamespace = "http:/wcompensar.caf/", partName = "parameter")
    public ConsultarUsuarioResponse consultarUsuario(
        @WebParam(name = "ConsultarUsuarioRequest", targetNamespace = "http:/wcompensar.caf/", partName = "parameter")
        ConsultarUsuarioRequest parameter)
        throws FaultMessage
    ;

}
