
package wcompensar.caf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ISICOM-CAF.serviceagent", targetNamespace = "http://WCompensar/CAF", wsdlLocation = "http://ec2-3-134-84-146.us-east-2.compute.amazonaws.com:8080/castlemock/mock/soap/project/86pnAI/CAFSoapEndpoint?WSDL")
public class ISICOMCAFServiceagent
    extends Service
{

    private final static URL ISICOMCAFSERVICEAGENT_WSDL_LOCATION;
    private final static WebServiceException ISICOMCAFSERVICEAGENT_EXCEPTION;
    private final static QName ISICOMCAFSERVICEAGENT_QNAME = new QName("http://WCompensar/CAF", "ISICOM-CAF.serviceagent");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ec2-3-134-84-146.us-east-2.compute.amazonaws.com:8080/castlemock/mock/soap/project/86pnAI/CAFSoapEndpoint?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISICOMCAFSERVICEAGENT_WSDL_LOCATION = url;
        ISICOMCAFSERVICEAGENT_EXCEPTION = e;
    }

    public ISICOMCAFServiceagent() {
        super(__getWsdlLocation(), ISICOMCAFSERVICEAGENT_QNAME);
    }

    public ISICOMCAFServiceagent(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISICOMCAFSERVICEAGENT_QNAME, features);
    }

    public ISICOMCAFServiceagent(URL wsdlLocation) {
        super(wsdlLocation, ISICOMCAFSERVICEAGENT_QNAME);
    }

    public ISICOMCAFServiceagent(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISICOMCAFSERVICEAGENT_QNAME, features);
    }

    public ISICOMCAFServiceagent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISICOMCAFServiceagent(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CAFSoap
     */
    @WebEndpoint(name = "CAFSoapEndpoint")
    public CAFSoap getCAFSoapEndpoint() {
        return super.getPort(new QName("http://WCompensar/CAF", "CAFSoapEndpoint"), CAFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CAFSoap
     */
    @WebEndpoint(name = "CAFSoapEndpoint")
    public CAFSoap getCAFSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://WCompensar/CAF", "CAFSoapEndpoint"), CAFSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns InformacionUsuarioSoap
     */
    @WebEndpoint(name = "InformacionUsuarioSoapEndpoint1")
    public InformacionUsuarioSoap getInformacionUsuarioSoapEndpoint1() {
        return super.getPort(new QName("http://WCompensar/CAF", "InformacionUsuarioSoapEndpoint1"), InformacionUsuarioSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformacionUsuarioSoap
     */
    @WebEndpoint(name = "InformacionUsuarioSoapEndpoint1")
    public InformacionUsuarioSoap getInformacionUsuarioSoapEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://WCompensar/CAF", "InformacionUsuarioSoapEndpoint1"), InformacionUsuarioSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISICOMCAFSERVICEAGENT_EXCEPTION!= null) {
            throw ISICOMCAFSERVICEAGENT_EXCEPTION;
        }
        return ISICOMCAFSERVICEAGENT_WSDL_LOCATION;
    }

}
